services:
    _defaults:
        public: true

    bugbuster_online.post_login_listener:
        class: "BugBuster\\OnlineBundle\\EventListener\\PostLoginListener"
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@security.http_utils'
            - '@contao.routing.scope_matcher'
            - '@security.helper'
            - '%session.storage.options%'
            - '@logger'
            - '%kernel.secret%'
        tags:
            - name: 'kernel.event_listener'

    # bugbuster_online.post_logout_listener:
    #     class: "BugBuster\\OnlineBundle\\EventListener\\PostLogoutListener"
    #     tags:
    #         - { name: contao.hook, hook: postLogout, method: onPostLogout, priority: 0 }

    bugbuster_online.post_logout_listener:
        class: "BugBuster\\OnlineBundle\\EventListener\\PostLogoutListener"
        arguments:
            - '@security.http_utils'
            - '@contao.routing.scope_matcher'
            - '@security.helper'
            - '@logger'
            - '%kernel.secret%'
        tags:
            - name: 'kernel.event_listener'

    # bugbuster_online.post_authenticate_listener:
    #     class: "BugBuster\\OnlineBundle\\EventListener\\PostAuthenticateListener"
    #     tags:
    #         - { name: contao.hook, hook: postAuthenticate, method: onPostAuthenticate, priority: 0 }


    # contao.listener.security.logout:
    #     class: Contao\CoreBundle\EventListener\Security\LogoutListener
    #     arguments:
    #         - '@security.http_utils'
    #         - '@contao.routing.scope_matcher'
    #         - '@security.helper'
    #         - '@logger'
    #     tags:
    #         - kernel.event_listener