services:
    _defaults:
        public: true

    bugbuster_online.post_login_listener:
        class: "BugBuster\\OnlineBundle\\EventListener\\PostLoginListener"
        arguments:
            - '@contao.routing.scope_matcher'
            - '@security.helper'
            - '%kernel.secret%'
            - '@database_connection'
            - '@logger'
            - '%session.storage.options%'
        tags:
            - name: 'kernel.event_listener'

    bugbuster_online.post_logout_listener:
        class: "BugBuster\\OnlineBundle\\EventListener\\PostLogoutListener"
        arguments:
            - '@contao.routing.scope_matcher'
            - '@security.helper'
            - '%kernel.secret%'
            - '@database_connection'
            - '@logger'
        tags:
            - name: 'kernel.event_listener'

    bugbuster_online.post_authenticate_listener:
        class: BugBuster\OnlineBundle\EventListener\PostAuthenticateListener
        arguments:
            - '@security.helper'
            - '@database_connection'
            - '%kernel.secret%'
            - '@logger'
        tags:
            - { name: 'kernel.event_listener' }
